import type { Metadata } from "next";
import Link from "next/link";

// generateMetadata runs on the server before the page renders.
// It receives the same props as the page component, so you can use
// the dynamic segment to build a unique title for each URL.
export async function generateMetadata(
  props: PageProps<"/dynamic/[name]">
): Promise<Metadata> {
  const { name } = await props.params;
  return {
    title: `Dynamic page — ${name}`,
    description: `This is the page for the "${name}" segment.`,
  };
}

// The folder is named [name] — the brackets make it a dynamic segment.
// Whatever is in the URL at that position becomes available as params.name.
//
// In this version of Next.js, params is a Promise, so we await it.
export default async function DynamicPage(props: PageProps<"/dynamic/[name]">) {
  const { name } = await props.params;

  return (
    <main className="max-w-2xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold mb-4">Dynamic Routes</h1>

      <p className="text-zinc-600 dark:text-zinc-400 mb-2">
        This file is at <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">app/dynamic/[name]/page.tsx</code>.
        The <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">[name]</code> folder matches any URL segment.
      </p>

      <p className="text-zinc-600 dark:text-zinc-400 mb-8">
        Current value of <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">name</code>:
      </p>

      <div className="bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded p-6 mb-8">
        <p className="text-5xl font-bold">{name}</p>
      </div>

      {/* Metadata explanation */}
      <div className="bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded p-4 mb-8 space-y-2 text-sm">
        <p className="font-semibold">Metadata for this page (check the browser tab):</p>
        <p className="text-zinc-500">title: <span className="text-zinc-800 dark:text-zinc-200 font-mono">Dynamic page — {name}</span></p>
        <p className="text-zinc-500">description: <span className="text-zinc-800 dark:text-zinc-200 font-mono">This is the page for the &quot;{name}&quot; segment.</span></p>
        <p className="text-zinc-400 pt-1">
          Generated by <code className="bg-zinc-200 dark:bg-zinc-700 px-1 rounded">generateMetadata()</code> — re-runs for each unique URL.
        </p>
      </div>

      <p className="text-sm text-zinc-500 mb-3">Try different URLs:</p>
      <div className="flex gap-3 flex-wrap">
        {["world", "alice", "bob", "next-js"].map((slug) => (
          <Link
            key={slug}
            href={`/dynamic/${slug}`}
            className="px-4 py-2 border border-zinc-300 dark:border-zinc-700 rounded text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800"
          >
            /dynamic/{slug}
          </Link>
        ))}
      </div>
    </main>
  );
}
